include: /build/gitlab-ci.yml

variables:
  PROJECT_PATH: "sosy-lab/software/cpachecker"
  GH_REF: "github.com/sosy-lab/cpachecker"
  # Version of https://gitlab.com/sosy-lab/software/refaster/ to use
  REFASTER_REPO_REVISION: 1c7b66df1ee6460c3a7b04bc4495f440a093ece7
  # Needs to be synchronized with Error Prone version in lib/ivy.xml
  REFASTER_VERSION: 2.3.4


build:jdk-14:
  variables:
    # https://github.com/google/error-prone/issues/1106
    ANT_PROPS_BUILD: "-Divy.disable=true -Derrorprone.disable=true"


.binary_check: &binary_check
  stage: checks

.configuration-checks: &configuration-checks
  <<: *binary_check
  script: "ant $ANT_PROPS_CHECKS configuration-checks"
  artifacts:
    paths:
      - "ConfigurationChecks.html"
      - "hs_err_pid*.log"
    when: always

configuration-checks:jdk-11:
  <<: *configuration-checks
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  image: ${CI_REGISTRY_IMAGE}/test:jdk-11

configuration-checks:jdk-14:
  <<: *configuration-checks
  dependencies:
    - build-dependencies
    - build:jdk-14
  needs:
    - build-dependencies
    - build:jdk-14
  image: ${CI_REGISTRY_IMAGE}/test:jdk-14


configuration-documentation:
  <<: *binary_check
  script:
    - "cp doc/ConfigurationOptions.txt doc/ConfigurationOptions.txt.old"
    - "ant $ANT_PROPS_CHECKS build-documentation"
    - "diff doc/ConfigurationOptions.txt.old doc/ConfigurationOptions.txt"
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11


configuration-plot:
  stage: checks
  script:
    - "mkdir -p output"
    - "touch output/AssumptionAutomaton.txt"
    - "scripts/configViz.py > ConfigurationPlot.dot"
    - "dot -Tsvg ConfigurationPlot.dot -O"
  dependencies: []
  artifacts:
    paths:
      - "ConfigurationPlot.dot.svg"


.python-unit-tests: &python-unit-tests
  <<: *binary_check
  script: "ant $ANT_PROPS_CHECKS python-unit-tests"

python-unit-tests:jdk-11:
  <<: *python-unit-tests
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  image: ${CI_REGISTRY_IMAGE}/test:jdk-11

python-unit-tests:jdk-14:
  <<: *python-unit-tests
  dependencies:
    - build-dependencies
    - build:jdk-14
  needs:
    - build-dependencies
    - build:jdk-14
  image: ${CI_REGISTRY_IMAGE}/test:jdk-14


javascript-unit-tests:
  stage: checks
  dependencies: []
  image: node:8.10.0 # This version is also provided by Ubuntu 18.04
  before_script:
    - cd src/org/sosy_lab/cpachecker/core/counterexample/
    - npm install
  script:
    - npm test
  cache:
    paths:
    - "src/org/sosy_lab/cpachecker/core/counterexample/node_modules/"
  artifacts:
    paths:
      - src/org/sosy_lab/cpachecker/core/counterexample/unit_testing_report.html
    when: always


build-docker:test:java-node:
  extends: .build-docker
  variables:
    DOCKERFILE: build/gitlab-ci.Dockerfile.java-node
    IMAGE: /test:java-node

build-docker:release:
  extends: .build-docker
  variables:
    DOCKERFILE: build/Dockerfile.release
    IMAGE: ":1.9"
    EXTRA_ARGS: "--destination $CI_REGISTRY_IMAGE:latest"


javascript-e2e-tests:
  stage: checks
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  image: ${CI_REGISTRY_IMAGE}/test:java-node
  before_script:
      # generate example report
    - scripts/cpa.sh -predicateAnalysis test/programs/simple/SSAMap-bug_false-unreach-label.c
    - cd src/org/sosy_lab/cpachecker/core/counterexample/
    - npm install
    - "./node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome $(dpkg-query --showformat='${Version}' --show chromium-browser)"
  script:
    - npm run e2e-test
  cache:
    paths:
    - src/org/sosy_lab/cpachecker/core/counterexample/node_modules/
  artifacts:
    paths:
      - output/Counterexample.1.html
      - src/org/sosy_lab/cpachecker/core/counterexample/e2e-tests-report
    when: always
  allow_failure: true # tests are currently racy (cf. #520)


# Checks for Python code
check-format-python:
  stage: checks
  dependencies: []
  image: python
  before_script:
    - pip install black
  script:
    - black . --check --diff

flake8:
  stage: checks
  dependencies: []
  image: python
  before_script:
    - pip install flake8-awesome
  script:
    - flake8
  allow_failure: true # need to fix existing code first


build-tar:
  stage: checks
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  script: "ant $ANT_PROPS_CHECKS dist-unix -Dnamet=cpachecker"
  artifacts:
    paths:
      - "cpachecker.tar.bz2"
  only:
    refs:
      - trunk

deploy-docker:
  stage: deploy
  dependencies:
    - build-tar
  extends: .build-docker
  variables:
    DOCKERFILE: build/Dockerfile.dev
    IMAGE: ":dev"
    EXTRA_ARGS: "--context dir://."
  only:
    refs:
      - trunk


# No coverage is computed for CPAchecker
unit-tests:jdk-11:
  script: "ant $ANT_PROPS_CHECKS unit-tests"

unit-tests:jdk-14:
  script: "ant $ANT_PROPS_CHECKS unit-tests"


# Disable some checks because they are not used for CPAchecker
check-format:
  only: []

javadoc:
  only: []
